### PR TITLE
Fix Curse of the Empty Lord morytania legs list

### LINKED ISSUE #643: Curse of the empty lord Incorrect infortmation
It says you can bring a ghostspeak amulet, or any pair of Morytania legs. However only Morytania legs 2 and upward work.

### PR DESCRIPTION
**Pull request by Felanbird**
I'm not actually sure the reason why `ItemID.MORYTANIA_LEGS = 5093` was on here, I can't tell if it's an ancient version of the legs before some old diary change or just a non-existant database item

Fixes #643

### CODE REVIEW

File: src/main/java/com/questhelper/quests/curseoftheemptylord/CurseOfTheEmptyLord.java [hunk 1]
```diff
@@ -131,8 +131,8 @@ public void setupItemRequirements()
 	{
 		ringOfVis = new ItemRequirement("Ring of visibility", ItemID.RING_OF_VISIBILITY, 1, true);
 		ghostspeak = new ItemRequirement("Ghostspeak amulet", ItemID.GHOSTSPEAK_AMULET, 1, true);
-		ghostspeakItems = new ItemRequirement("Ghostspeak amulet or any pair of morytania legs", ItemID.GHOSTSPEAK_AMULET, 1, true);
-		ghostspeakItems.addAlternates(ItemID.MORYTANIA_LEGS, ItemID.MORYTANIA_LEGS_1, ItemID.MORYTANIA_LEGS_2, ItemID.MORYTANIA_LEGS_3, ItemID.MORYTANIA_LEGS_4);
+		ghostspeakItems = new ItemRequirement("Ghostspeak amulet or Morytania legs (2) or better", ItemID.GHOSTSPEAK_AMULET, 1, true);
+		ghostspeakItems.addAlternates(ItemID.MORYTANIA_LEGS_2, ItemID.MORYTANIA_LEGS_3, ItemID.MORYTANIA_LEGS_4);
```
Comment (Felanbird) [inline src/main/java/com/questhelper/quests/curseoftheemptylord/CurseOfTheEmptyLord.java:135]:
```suggestion
		ghostspeakItems.addAlternates(ItemID.MORYTANIA_LEGS, ItemID.MORYTANIA_LEGS_2, ItemID.MORYTANIA_LEGS_3, ItemID.MORYTANIA_LEGS_4);
```
Suggestion for easy re-implementation in case I'm wrong about the purpose of this item

**Review by Zoinkwiz — APPROVED** [review]
Looks good, i think it should be fine without MORYTANIA_LEGS included.
